### ISSUE TITLE
AndroidQ 录制视频异常 崩溃

### ISSUE THREAD

**Issue by yujiezhao** [lll-01/VideoRecorder#15]
AndroidQ 录制视频异常 崩溃

**Comment by erleizh** [comment]
所以你不准备提供点日志吗 。

**Comment by yujiezhao** [comment]
2019-10-29 13:49:12.971 30087-30087/com.erlei.videorecorder E/MultiPartRecorder: /storage/emulated/0/Android/data/com.erlei.videorecorder/cache/MultiPartRecorder/2019-10-29-06-49-12-964.mp4
2019-10-29 13:49:13.264 30087-30843/com.erlei.videorecorder E/GraphicExt: GraphicExtModuleLoader::CreateGraphicExtInstance false
2019-10-29 13:49:13.317 30087-30843/com.erlei.videorecorder E/MultiPartRecorder-MultiPartRecorder: supportedType:c2.android.aac.encoder,MIME=audio/mp4a-latm
2019-10-29 13:49:13.317 30087-30843/com.erlei.videorecorder E/MultiPartRecorder-MultiPartRecorder: selected codec: c2.android.aac.encoder
2019-10-29 13:49:13.318 30087-30843/com.erlei.videorecorder E/MultiPartRecorder-MultiPartRecorder: format: {channel-mask=16, sample-rate=44100, mime=audio/mp4a-latm, channel-count=1, aac-profile=2, bitrate=64000}
2019-10-29 13:49:13.410 30087-30843/com.erlei.videorecorder E/MultiPartRecorder-MultiPartRecorder: prepare finishing
2019-10-29 13:49:13.510 30087-30858/com.erlei.videorecorder E/ACodec: [OMX.MTK.VIDEO.ENCODER.AVC] ERROR(0x80001005)
2019-10-29 13:49:13.510 30087-30858/com.erlei.videorecorder E/ACodec: signalError(omxError 0x80001005, internalError -2147483648)
2019-10-29 13:49:13.511 30087-30857/com.erlei.videorecorder E/MediaCodec: Codec reported err 0x80001005, actionCode 0, while in state 6
2019-10-29 13:49:13.512 30087-30858/com.erlei.videorecorder E/ACodec: [OMX.MTK.VIDEO.ENCODER.AVC] ERROR(0x80001005)
2019-10-29 13:49:13.513 30087-30858/com.erlei.videorecorder E/ACodec: signalError(omxError 0x80001005, internalError -2147483648)
2019-10-29 13:49:13.514 30087-30844/com.erlei.videorecorder E/AndroidRuntime: FATAL EXCEPTION: MediaVideoEncoder
    Process: com.erlei.videorecorder, PID: 30087
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2789)
        at com.erlei.videorecorder.encoder1.MediaEncoder.drain(MediaEncoder.java:295)
        at com.erlei.videorecorder.encoder1.MediaEncoder.run(MediaEncoder.java:153)
        at java.lang.Thread.run(Thread.java:919)
2019-10-29 13:49:13.514 30087-30858/com.erlei.videorecorder E/ACodec: [OMX.MTK.VIDEO.ENCODER.AVC] ERROR(0x80001005)

**Comment by yujiezhao** [comment]
我把 布局文件 `  <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="400dp">`
改成了 全局显示  `<FrameLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">` 后问题就出现了

**Comment by erleizh** [comment]
看起来像是音频编码器异常 ，祝你好运  - -

**Comment by yujiezhao** [comment]
好样的 兄滴~   我慢慢看吧

**Comment by yujiezhao** [comment]
问题解决了   MediaVideoEncoder 类里 
在 初始化  final MediaFormat format = MediaFormat.createVideoFormat(MIME_TYPE, mVideoSize.getWidth(), mVideoSize.getHeight());        
MediaFormat    mVideoSize.getWidth() 指的是 布局中 `        <TextureView
            android:id="@+id/textureView"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />` TextureView的高度， 这样就会导致 指定的高度，宽度 MediaFormat 识别不了。产生异常。

 解决方法 ： `    private  Size PreviewSize;
    public MediaVideoEncoder(MediaMuxerWrapper muxer, VideoRecorder.Config config) {
        super(muxer,config);
        mVideoSize = config.getCameraController().getSurfaceSize();
        PreviewSize = config.getCameraController().getCameraSize();
        mIFrameInterval = config.getIFrameInterval();
        mBitRate = config.getVideoBitRate() <= 0 ? calcBitRate() : config.getVideoBitRate();
        mFrameRate = config.getFrameRate() <= 0 ? FRAME_RATE : config.getFrameRate();
    }`

在构造函数中添加        PreviewSize = config.getCameraController().getCameraSize();  获取摄像头最接近的 Size 。

替换原来的初始化 MediaFormat    `     final MediaFormat format = MediaFormat.createVideoFormat(MIME_TYPE, PreviewSize.getHeight(), PreviewSize.getWidth());`

就可以了 。

**Comment by erleizh** [comment]
时间太久远了 ，我不确定会不会影响到离屏录制
