### ISSUE TITLE
 mCameraController.setPreviewFpsRange();  java.lang.IllegalStateException: camera == null  

### ISSUE THREAD

**Issue by anonym24** [lll-01/VideoRecorder#6]
Camera.CameraBuilder cameraBuilder = new Camera.CameraBuilder(this)
                        .useDefaultConfig()
                        .setFacing(android.hardware.Camera.CameraInfo.CAMERA_FACING_FRONT)
                        .setPreviewSize(new Size(1920, 1080))
                        .setRecordingHint(true)

        ....
                        
        mCameraController = mRecorder.getCameraController();

        mRecorder.startPreview();

I tried to set  `mCameraController.setPreviewFpsRange(new FpsRange(20000, 20000));` before `mRecorder.startPreview();` and after it 

but it fails in both cases

```
   java.lang.IllegalStateException: camera == null
                      at com.erlei.videorecorder.recorder.DefaultCameraController.checkCameraState(DefaultCameraController.java:475)
                      at com.erlei.videorecorder.recorder.DefaultCameraController.setPreviewFpsRange(DefaultCameraController.java:69)
                      
```

it would be great if I could set fps range during creating `CameraBuilder`

**Comment by anonym24** [comment]
In Camera.java we can add:

```
    private void setPreviewFpsRange(android.hardware.Camera.Parameters cameraParameters, FpsRange fpsRange) {
        List<FpsRange> supportedPreviewFpsRange = getSupportedPreviewFpsRange();
        if (supportedPreviewFpsRange.contains(fpsRange)) {
            cameraParameters.setPreviewFpsRange(fpsRange.min, fpsRange.max);
        }
    }
```

```
    private void setCameraParameters() {
        if (mCamera == null) return;
        android.hardware.Camera.Parameters cameraParameters = getParameters();
        if (cameraParameters == null) return;

        setPreviewFpsRange(cameraParameters, mBuilder.mFpsRange);
        ....
```


```
    public static class CameraBuilder {

        ....
        private FpsRange mFpsRange;

       ...
      public CameraBuilder setPreviewFpsRange(FpsRange fpsRange) {
            mFpsRange = fpsRange;
            return this;
        }
```
