### ISSUE TITLE
Camera.open method is called twice. It causes issue on KitKat 4.4

### ISSUE THREAD

**Issue by anonym24** [lll-01/VideoRecorder#8]
I tried next sample on 6.0.1 Marshmallow Device and it worked fine

But when I tried on 4.4 KitKat device then preview doesn't even work, at app start it updates only two frames and then it becomes frozen (always the same frame on preview)

```
private void testVideoRecording2() {

        ICameraPreview cameraPreview = new DefaultCameraPreview(mPreview);

        com.erlei.videorecorder.camera.Camera.CameraBuilder cameraBuilder =
                new com.erlei.videorecorder.camera.Camera.CameraBuilder(this)
                        .useDefaultConfig()
                        .setFacing(Camera.CameraInfo.CAMERA_FACING_BACK)
                        .setPreviewSize(new Size(1280, 720))
                        .setRecordingHint(true)
                        .setPreviewFpsRange(new FpsRange(30000, 30000))
                        .setFocusMode(android.hardware.Camera.Parameters.FOCUS_MODE_CONTINUOUS_VIDEO)
                        .setPreviewFrameCallback(new com.erlei.videorecorder.camera.Camera.PreviewCallback() {
                            @Override
                            public void onPreviewFrame(byte[] frame) {
                                Log.i(TAG, "onPreviewFrame " + frame.length);
                            }
                        });


        //视频效果管理器
        mEffectsManager = new EffectsManager();
        mEffectsManager.addEffect(new CanvasOverlayEffect() {
            private FPSCounterFactory.FPSCounter1 mCounter;
            Paint mPaint;

            @Override
            public void prepare(Size size) {
                super.prepare(size);
                mPaint = new Paint();
                mPaint.setColor(Color.YELLOW);
                mPaint.setAlpha(230);
                mPaint.setTextSize(40);
                mPaint.setStyle(Paint.Style.FILL);
                mPaint.setAntiAlias(true);

                mCounter = new FPSCounterFactory.FPSCounter1();
            }

            @Override
            protected void drawCanvas(Canvas canvas) {
                canvas.drawText("test", canvas.getWidth() / 2, canvas.getHeight() / 2, mPaint);
            }
        });

        VideoRecorder.Builder builder = new VideoRecorder.Builder(cameraPreview)
                .setCallbackHandler(new VideoRecorderHandler())
                .setLogFPSEnable(false)
                .setCameraBuilder(cameraBuilder)
                .setDrawTextureListener(mEffectsManager)
                .setOutPutPath(Environment.getExternalStorageDirectory().getAbsolutePath())
                .setFrameRate(30)
                .setChannelCount(1);

        //分段录制,回删支持
        MultiPartRecorder.Builder multiBuilder = new MultiPartRecorder.Builder(builder);
        mRecorder = multiBuilder
                .addPartListener(new MultiPartRecorder.VideoPartListener() {
                    @Override
                    public void onRecordVideoPartStarted(MultiPartRecorder.Part part) {
                        LogUtil.logd("onRecordVideoPartStarted \t" + part.toString());
                    }

                    @Override
                    public void onRecordVideoPartSuccess(MultiPartRecorder.Part part) {
                        LogUtil.logd("onRecordVideoPartSuccess \t" + part.toString());
                    }

                    @Override
                    public void onRecordVideoPartFailure(MultiPartRecorder.Part part) {
                        LogUtil.loge("onRecordVideoPartFailure \t" + part.file);
                        //mRecorderIndicator.removePart(part.file.getAbsolutePath());
                        mRecorder.removePart(part.file.getAbsolutePath());
                    }
                })
                .setMergeListener(new MultiPartRecorder.VideoMergeListener() {
                    @Override
                    public void onStart() {
                        LogUtil.logd("merge onStart");
                    }

                    @Override
                    public void onSuccess(File outFile) {
                        LogUtil.logd("merge Success \t" + outFile);
                
                    }

                    @Override
                    public void onError(Exception e) {
                        LogUtil.logd("merge Error \t" + e.toString());
                    }

                    /**
                     * 合并进度
                     *
                     * @param value 0 - 1
                     */
                    @Override
                    public void onProgress(float value) {
                        LogUtil.logd("merge onProgress \t" + value);
                    }

                })
                .setFileFilter(new MultiPartRecorder.FileFilter() {
                    @Override
                    public boolean filter(MultiPartRecorder.Part part) {
                        return part.duration > 1500;
                    }
                })
                .build();

        mCameraController = mRecorder.getCameraController();

        mRecorder.startPreview();

        mRecorder.startRecord();

        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                mRecorder.stopRecord();
                Log.i(TAG, "RecordFinished");
            }
        }, 7000);
    }
```

**Comment by anonym24** [comment]
Logs: (some error with  `java.lang.RuntimeException: Fail to connect to camera service`)

```
09-14 12:17:08.552 21272-21284/com.test.videorecorder V/SurfaceView: this = com.test.videorecorder.camera.JavaCameraView{42638f78 V.E..... ......I. 0,0-1280,720 #7f070007 app:id/SurfaceView} got resized: w=1280 h=720, cur w=-1 h=-1
09-14 12:17:09.251 31020-31049/com.example.android.mediarecorder D/dalvikvm: threadid=12: notify debugger
    threadid=12 (com.erlei.videorecorder.recorder.RenderThread): calling run()
09-14 12:17:09.251 31020-31020/com.example.android.mediarecorder E/VideoRecorder-VideoRecorder: startEncoder:begin
09-14 12:17:09.257 31020-31049/com.example.android.mediarecorder D/VideoRecorder-VideoRecorder: looper onLooperPrepared
09-14 12:17:09.259 31020-31050/com.example.android.mediarecorder E/VideoRecorder-VideoRecorder: startEncoder:begin
09-14 12:17:09.271 31020-31050/com.example.android.mediarecorder I/VideoRecorder-VideoRecorder: bitrate=10,55[Mbps]
09-14 12:17:09.273 31020-31049/com.example.android.mediarecorder D/VideoRecorder: EGLContext created, client version 3
09-14 12:17:09.277 31020-31049/com.example.android.mediarecorder D/VideoRecorder: OpenGL ES version: OpenGL ES 3.0
09-14 12:17:09.278 31020-31049/com.example.android.mediarecorder D/VideoRecorder: loadShader
09-14 12:17:09.293 31020-31049/com.example.android.mediarecorder D/VideoRecorder: Shader program is built OK
09-14 12:17:09.293 31020-31049/com.example.android.mediarecorder D/VideoRecorder: loadShader
09-14 12:17:09.299 31020-31049/com.example.android.mediarecorder D/VideoRecorder: Shader program is built OK
09-14 12:17:09.299 31020-31049/com.example.android.mediarecorder D/VideoRecorder: initSurfaceTexture
    deleteSurfaceTexture
    initTexOES
09-14 12:17:09.356 31020-31049/com.example.android.mediarecorder D/VideoRecorder: SupportedPreviewSizes		width :176	 height :144	 ratio : 1.2222222
    SupportedPreviewSizes		width :320	 height :240	 ratio : 1.3333334
09-14 12:17:09.356 31020-31049/com.example.android.mediarecorder D/VideoRecorder: SupportedPreviewSizes		width :352	 height :288	 ratio : 1.2222222
    SupportedPreviewSizes		width :480	 height :320	 ratio : 1.5
    SupportedPreviewSizes		width :480	 height :368	 ratio : 1.3043479
    SupportedPreviewSizes		width :640	 height :480	 ratio : 1.3333334
    SupportedPreviewSizes		width :720	 height :480	 ratio : 1.5
    SupportedPreviewSizes		width :800	 height :480	 ratio : 1.6666666
    SupportedPreviewSizes		width :864	 height :480	 ratio : 1.8
    SupportedPreviewSizes		width :800	 height :600	 ratio : 1.3333334
    SupportedPreviewSizes		width :960	 height :540	 ratio : 1.7777778
09-14 12:17:09.356 31020-31049/com.example.android.mediarecorder D/VideoRecorder: SupportedPreviewSizes		width :800	 height :800	 ratio : 1.0
    SupportedPreviewSizes		width :1280	 height :720	 ratio : 1.7777778
    SupportedPreviewSizes		width :1440	 height :1080	 ratio : 1.3333334
    SupportedPreviewSizes		width :1920	 height :1080	 ratio : 1.7777778
    SupportedPreviewSizes		width :1920	 height :1088	 ratio : 1.7647059
    requestPreviewSize ：1920x1080		 previewSize : 1920x1080
09-14 12:17:09.357 31020-31049/com.example.android.mediarecorder D/VideoRecorder: SupportedPictureSizes		width :320	 height :240	 ratio : 1.3333334
    SupportedPictureSizes		width :640	 height :480	 ratio : 1.3333334
    SupportedPictureSizes		width :1024	 height :768	 ratio : 1.3333334
09-14 12:17:09.357 31020-31049/com.example.android.mediarecorder D/VideoRecorder: SupportedPictureSizes		width :1280	 height :720	 ratio : 1.7777778
    SupportedPictureSizes		width :1280	 height :768	 ratio : 1.6666666
    SupportedPictureSizes		width :1280	 height :960	 ratio : 1.3333334
    SupportedPictureSizes		width :1600	 height :1200	 ratio : 1.3333334
09-14 12:17:09.357 31020-31049/com.example.android.mediarecorder D/VideoRecorder: SupportedPictureSizes		width :2048	 height :1536	 ratio : 1.3333334
    SupportedPictureSizes		width :2560	 height :1440	 ratio : 1.7777778
    SupportedPictureSizes		width :2560	 height :1920	 ratio : 1.3333334
    SupportedPictureSizes		width :3328	 height :1872	 ratio : 1.7777778
    SupportedPictureSizes		width :3264	 height :2448	 ratio : 1.3333334
    SupportedPictureSizes		width :3840	 height :2160	 ratio : 1.7777778
    SupportedPictureSizes		width :4160	 height :3120	 ratio : 1.3333334
    SupportedPictureSizes		width :4864	 height :2736	 ratio : 1.7777778
09-14 12:17:09.357 31020-31049/com.example.android.mediarecorder D/VideoRecorder: requestPictureSize ：1920x1080		 pictureSize : 2048x1536
09-14 12:17:09.369 31020-31049/com.example.android.mediarecorder D/VideoRecorder: flash-duty-max=1;	mnr-e=0;	zoom=0;	fb-smooth-level-max=4;	max-num-detected-faces-hw=15;	mtk-awb-s=true;	cap-mode=normal;	fb-touch-pos=-2000:-2000;	aflamp-mode-values=off,on,auto;	whitebalance=auto;	fb-slim-face-min=-4;	afeng-min-focus-step=0;	preview-format-values=yuv420sp,yuv420p,yuv420i-yyuvyy-3plane;	rotation=0;	jpeg-thumbnail-quality=100;	preview-format=yuv420sp;	mnr-s=true;	video-hdr-values=off;	pip-fps-zsd-on=24;	dynamic-frame-rate=true;	vrd-mfr-low=15;	iso-speed=auto;	face-beauty=false;	video-hdr=off;	hsvr-size-fps=640x480x120;	flash-mode-values=off,on,auto,red-eye,torch;	hue-values=low,middle,high;	aflamp-mode=off;	cshot-indicator-supported=true;	preview-frame-rate=30;	3dnr-mode-values=on,off;	vrd-mfr-max=30;	jpeg-thumbnail-width=160;	video-size=640x480;	scene-mode-values=auto,portrait,landscape,night,night-portrait,theatre,beach,snow,sunset,steadyphoto,fireworks,sports,party,candlelight,hdr;	mtk-shad-s=true;	feature-max-fps=24@VFB+EIS;	preview-fps-range-values=(5000,60000);	fb-slim-face-max=4;	contrast-values=low,middle,high;	fb-face-pos=-2000:-2000;	preview-size-values=176x144,320x240,352x288,480x320,480x368,640x480,720x480,800x480,800x600,864x480,960x540,1280x720,1440x1080,1920x1080,1920x1088,800x800;	fb-enlarge-eye-max=4;	preview-fps-range=5000,60000;	fb-enlarge-eye-min=-4;	min-exposure-compensation=-2;	antibanding=off;	max-num-focus-areas=1;	vertical-view-angle=49;	fb-smooth-level-min=-4;	flash-duty-min=0;	fb-skin-color=0;	video-stabilization-supported=true;	brightness_value=0;	vdr-cc2m-s=false;	saturation-values=low,middle,high;	eng-mfll-s=true;	stereo-image-refocus-values=on,off;	eng-mfll-e=false;	vdr-r4k2k-s=false;	mtk-123-shad-s=true;	flash-duty-value=-1;	vrd-mfr-e=true;	sv2-s=3;	vrd-mfr-high=30;	edge=middle;	picture-format-values=jpeg;	iso-speed-values=auto,100,200,400,800,1600;	sr-shad-s=true;	m-ss=0;	exposure-compensation-step=1.0;	eng-s-shad-t=0;	m-sr-g=0;	stereo-depth-af-values=on,off;	picture-size=2048x1536;	vrd-mfr-s=true;	saturation=middle;	whitebalance-values=auto,incandescent,fluorescent,warm-fluorescent,daylight,cloudy-daylight,twilight,shade;	picture-format=jpeg;	cshot-indicator=true;	fb-enlarge-eye=0;	pip-fps-zsd-off=30;	afeng-max-focus-step=1023;	preferred-preview-size-for-video=1920x1080;	flash-step-min=0;	hue=middle;	recording-hint=false;	video-stabilization=false;	zoom-supported=true;	fb-smooth-level=0;	vrd-mfr-min=15;	fb-sharp=0;	contrast=middle;	vdr-r2m-s=true;	scene-mode=auto;	jpeg-quality=100;	face-beauty-supported=true;	stereo-distance-measurement=off;	burst-num=1;	dynamic-frame-rate-supported=true;	vdr-r=0;	video-size-values=176x144,480x320,640x480,864x480,1280x720,1920x1080,3840x2160;	preview-size=1920x1080;	focal-length=3.5;	stereo-depth-af=off;	cap-mode-values=normal,face_beauty,continuousshot,smileshot,bestshot,autorama,mav,asd,motiontrack;	preview-frame-rate-values=20,15,24,30,120;	max-num-metering-areas=9;	fb-sharp-max=4;	sr-awb-s=true;	sensor-type=252;	focus-fs-fi=0;	3dnr-mode=on;	focus-mode-values=auto,macro,infinity,continuous-picture,continuous-video,manual,fullscan;	vhdr-s=0;	focus-fs-fi-min=0;	fb-sharp-min=-4;	jpeg-thumbnail-size-values=0x0,160x128,320x240;	sen-mode-s=0;	zoom-ratios=100,114,132,151,174,200,229,263,303,348,400;	flash-step-max=0;	eng-shad-t=0;	picture-size-values=320x240,640x480,1024x768,1280x720,1280x768,1280x960,1600x1200,2048x1536,2560x1440,2560x1920,3264x2448,3328x1872,3840x2160,4160x3120,4864x2736;	edge-values=low,middle,high;	hsvr-size-fps-values=640x480x120;	horizontal-view-angle=63;	fb-extreme-beauty-supported=false;	brightness=middle;	jpeg-thumbnail-height=128;	fb-slim-face=0;	mfb-values=off,mfll,ais;	smooth-zoom-supported=true;	capfname=/sdcard/DCIM/cap00;	zsd-mode=off;	focus-mode=continuous-video;	fb-skin-color-max=4;	auto-whitebalance-lock-supported=true;	fb-skin-color-min=-4;	video-frame-format=yuv420p;	max-num-detected-faces-sw=0;	sv1-s=3;	max-exposure-compensation=2;	mfb=off;	max-num-ot=1;	video-snapshot-supported=true;	exposure-compensation=0;	brightness-values=low,middle,high;	flash-mode=auto;	effect-va
09-14 12:17:09.406 31020-31050/com.example.android.mediarecorder V/VideoRecorder: prepare:
    selectAudioCodec:
09-14 12:17:09.406 31020-31050/com.example.android.mediarecorder E/VideoRecorder-VideoRecorder: supportedType:OMX.MTK.VIDEO.ENCODER.MPEG4,MIME=video/mp4v-es
    supportedType:OMX.MTK.VIDEO.ENCODER.H263,MIME=video/3gpp
    supportedType:OMX.MTK.VIDEO.ENCODER.AVC,MIME=video/avc
    supportedType:OMX.MTK.VIDEO.ENCODER.VPX,MIME=video/x-vnd.on2.vp8
    supportedType:OMX.MTK.VIDEO.ENCODER.HEVC,MIME=video/hevc
    supportedType:OMX.MTK.AUDIO.ENCODER.AMR,MIME=audio/3gpp
    supportedType:OMX.MTK.AUDIO.ENCODER.AWB,MIME=audio/amr-wb
    supportedType:OMX.MTK.AUDIO.ENCODER.AAC,MIME=audio/mp4a-latm
    selected codec: OMX.MTK.AUDIO.ENCODER.AAC
    format: {bitrate=64000, channel-count=1, aac-profile=2, mime=audio/mp4a-latm, sample-rate=44100, channel-mask=16}
09-14 12:17:09.419 31020-31050/com.example.android.mediarecorder E/VideoRecorder-VideoRecorder: prepare finishing
09-14 12:17:09.419 31020-31050/com.example.android.mediarecorder I/VideoRecorder-VideoRecorder: startRecording
    startRecording
09-14 12:17:09.427 31020-31088/com.example.android.mediarecorder V/VideoRecorder: AudioThread:start audio recording
09-14 12:17:09.643 31020-31052/com.example.android.mediarecorder I/VideoRecorder-VideoRecorder: INFO_OUTPUT_FORMAT_CHANGED
09-14 12:17:09.644 31020-31052/com.example.android.mediarecorder I/VideoRecorder-VideoRecorder: addTrack:trackNum=2,trackIx=0,format={channel-count=1, mime=audio/mp4a-latm, csd-0=java.nio.ByteArrayBuffer[position=0,limit=2,capacity=2], sample-rate=44100, what=1869968451}
09-14 12:17:09.644 31020-31052/com.example.android.mediarecorder D/VideoRecorder-VideoRecorder: start:
09-14 12:17:09.832 31020-31049/com.example.android.mediarecorder D/VideoRecorder: openCamera 1536916629832
09-14 12:17:09.833 31020-31049/com.example.android.mediarecorder D/VideoRecorder: onSizeChanged(1280x720)
    updateCoordinateTransform
09-14 12:17:09.834 31020-31049/com.example.android.mediarecorder D/VideoRecorder-VideoRecorder: rotation=1
09-14 12:17:09.834 31020-31049/com.example.android.mediarecorder D/VideoRecorder-VideoRecorder: cameraSize = 1920.0x1080.0
    surfaceSize = 1280.0x720.0
    cameraAspectRatio = 1.7777778		 surfaceAspectRatio = 1.7777778
    scalex = 1.5		 scaley = 1.5
    scale = 0.6666667		 dx = 0.0		 dy = 0.0
09-14 12:17:09.834 31020-31049/com.example.android.mediarecorder D/VideoRecorder: initFBO(1280x720)
    deleteFBO(0x0)
    deleteTex
09-14 12:17:09.843 31020-31049/com.example.android.mediarecorder D/VideoRecorder: initFBO status: 0
    initFBO success, status: 36053
09-14 12:17:09.901 31020-31049/com.example.android.mediarecorder E/VideoRecorder: java.lang.RuntimeException: Fail to connect to camera service
09-14 12:17:09.901 31020-31049/com.example.android.mediarecorder W/System.err:     at android.hardware.Camera.native_setup(Native Method)
        at android.hardware.Camera.<init>(Camera.java:474)
        at android.hardware.Camera.open(Camera.java:429)
        at com.erlei.videorecorder.camera.Camera.open(Camera.java:162)
        at com.erlei.videorecorder.recorder.DefaultCameraController.openCamera(DefaultCameraController.java:136)
        at com.erlei.videorecorder.recorder.VideoRecorder.onPrepared(VideoRecorder.java:242)
        at com.erlei.videorecorder.recorder.RenderThread.onLooperPrepared(RenderThread.java:102)
        at android.os.HandlerThread.run(HandlerThread.java:60)
        at com.erlei.videorecorder.recorder.RenderThread.run(RenderThread.java:45)
```

**Comment by anonym24** [comment]
I noticed that it tries to open camera twice https://github.com/lll-01/VideoRecorder/blob/master/VideoRecorderCore/src/main/java/com/erlei/videorecorder/camera/Camera.java#L162

```
09-14 12:26:11.401 32383-32411/com.example.android.mediarecorder I/VideoRecorder: openCamera
09-14 12:26:11.830 32383-32411/com.example.android.mediarecorder D/VideoRecorder: openCamera 1536917171830
    onSizeChanged(1280x720)
    updateCoordinateTransform
09-14 12:26:11.880 32383-32411/com.example.android.mediarecorder I/VideoRecorder: openCamera
09-14 12:26:11.882 32383-32411/com.example.android.mediarecorder W/System.err:     at android.hardware.Camera.native_setup(Native Method)
        at android.hardware.Camera.<init>(Camera.java:474)
        at android.hardware.Camera.open(Camera.java:429)
        at com.erlei.videorecorder.camera.Camera.open(Camera.java:163)
        at com.erlei.videorecorder.recorder.DefaultCameraController.openCamera(DefaultCameraController.java:136)
        at com.erlei.videorecorder.recorder.VideoRecorder.onPrepared(VideoRecorder.java:242)
        at com.erlei.videorecorder.recorder.RenderThread.onLooperPrepared(RenderThread.java:102)
        at android.os.HandlerThread.run(HandlerThread.java:60)
        at com.erlei.videorecorder.recorder.RenderThread.run(RenderThread.java:45)
09-14 12:26:11.882 32383-32411/com.example.android.mediarecorder D/VideoRecorder: openCamera 1536917171882

```

so it fails to open Camera for the second time but do we even need to do it anyway?

**Comment by anonym24** [comment]
it called twice from https://github.com/lll-01/VideoRecorder/blob/master/VideoRecorderCore/src/main/java/com/erlei/videorecorder/recorder/DefaultCameraController.java#L136

**Comment by anonym24** [comment]
Mb this line of code is useless https://github.com/lll-01/VideoRecorder/blob/master/VideoRecorderCore/src/main/java/com/erlei/videorecorder/recorder/RenderThread.java#L102

because we already open camera from https://github.com/lll-01/VideoRecorder/blob/master/VideoRecorderCore/src/main/java/com/erlei/videorecorder/recorder/RenderThread.java#L94

**Comment by erleizh** [comment]
对 ，从`VideoRecorder.java`删除这一行就行了
```
    @Override
    public void onPrepared(EglCore eglCore) {
       // mConfig.cameraController.openCamera(getPreviewTexture());
    }

```
